spring:
  application:
    name: template
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tempdb
    username: temp
    password: temp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect